# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5004a1f215f67494792ef07c0e376af7bd9187cde31ae9623b95b776ca9a08e3862802e0f6608f665a6368de508e207476597104d055991d4299c6529ab65268

test:
  secret_key_base: 3300d09717afdeed06f13fd19f10cc41fb5573441e5ee72665f67702c4bdc97ae5432d3ca1d5e74ef5ae32a7764375b1e001418cbb6f5a0bb224d60ae92b2264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
